"""encounters.draft_note: autosaved unsaved-edit workspace state

Revision ID: 5c68613c291a
Revises: 3e2a564db10f
Create Date: 2026-07-08 22:52:17.152067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5c68613c291a'
down_revision: Union[str, Sequence[str], None] = '3e2a564db10f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('encounters', sa.Column('draft_note', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('encounters', 'draft_note')
    # ### end Alembic commands ###
